services:
  - type: web
    name: 100gates-bot
    env: python
    plan: free
    buildCommand: |
      python3.11 -m pip install --upgrade pip
      python3.11 -m pip install -r requirements.txt
    startCommand: python3.11 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 7565894498:AAE35txlRa2uTbZ7lBJWvrM9ExAtGYRtfuI
      - key: DATABASE_URL
        fromDatabase:
          name: gatesdb
          property: connectionString
      - key: WEBHOOK_URL
        value: https://100gates-bot.onrender.com
      - key: SECRET_KEY
        generateValue: true
      - key: QUESTION_TIMEOUT
        value: 30
      - key: TOTAL_GATES
        value: 100
      - key: PRIZE_POOL_PERCENTAGE
        value: 69
      - key: ADMIN_TELEGRAM_IDS
        sync: false

databases:
  - name: gatesdb
    databaseName: gatesdb
    user: gatesuser
    plan: free 